### ISSUE TITLE
multi socket

### ISSUE THREAD

**Issue by rebotnix** [Eyevinn/node-srt#1]
i will test it by myself, but does it support multiple socket client connection on the connected port?

**Comment by birme** [comment]
Hi, not just yet. I can let you know once available!

**Comment by themaxsmith** [comment]
This project definitely excites me. SRT is the future & I could see this as a good server media server.

**Comment by tchakabam** [comment]
@rebotnix If this is what you meant: There is now a SRTServer utilty class that supports accepting multiple connections implemented via the novel async API. But you can also implement your own server anyhow using the `accept` method and event-poll any listening socket(s) - using the async API that is, it will be pretty much impossible to get a server going with the plain blocking one on the native binding. So the srt-server/connection classes we added are specifically there to cover this general use-case and build apps upon.

But I haven't tested it yet with several connections in a proper prod-case tbh :)

Regarding this, I am atm thinking that you may need two AsyncSRTs (thread instances) to operate on `accept` which within the async-SRT worker thread is a blocking op (sits until a new client comes up), and otoh do in the second thread r/w ops on all the connections independently of awaiting a new connection in the first thread. You however in principle should not need more than one thread do all r/w ops on the client connection sockets. 

@birme We may need to refine the SRTConnection class in the srt-server module to enable that as the default working mode (the server maintaing two AsyncSRTs instead of as currently one).

**Comment by rebotnix** [comment]
I would like to test it, but i can´t get any SRT encoder to work with the latest NODEJS of this project. Maybe i do something wrong and i open a new issue to understand that the problem can be.

**Comment by tchakabam** [comment]
> i can´t get any SRT encoder to work with the latest NODEJS of this project

what exactly do you reference to by "NODEJS" here? 

yes, let's try to find out what your problem is on the other tickets you opened :)

**Comment by tchakabam** [comment]
@rebotnix The issue seen by you was this one I think: https://github.com/Eyevinn/node-srt/issues/17 

did you try the fix?
